cmake_minimum_required(VERSION 3.21)
# Exercise the production option logic without requiring each compiler/platform.
set(APPLE "${TEST_APPLE}")
set(CMAKE_CXX_COMPILER_ID "${TEST_COMPILER_ID}")
set(LEAN_EXTRA_LINKER_FLAGS "existing-flags")
include("${CMAKE_CURRENT_LIST_DIR}/../../../src/cmake/Modules/LeanMetal.cmake")
if(NOT "${USE_METAL}" STREQUAL "${EXPECTED}")
  message(FATAL_ERROR "Expected USE_METAL=${EXPECTED}, got ${USE_METAL}")
endif()
if(USE_METAL)
  set(expected_flags "existing-flags -framework Metal -framework Foundation")
else()
  set(expected_flags "existing-flags")
endif()
if(NOT LEAN_EXTRA_LINKER_FLAGS STREQUAL expected_flags)
  message(FATAL_ERROR "Unexpected linker flags: ${LEAN_EXTRA_LINKER_FLAGS}")
endif()
